FROM nvidia/cuda:12.2.2-base-ubuntu22.04

ENV PATH=/opt/conda/bin:$PATH

RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    curl \
    git \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o ~/miniconda.sh \
    && sh ~/miniconda.sh -b -p /opt/conda \
    && rm ~/miniconda.sh
COPY . .

COPY environment_setup.sh environment_setup.sh
RUN ./environment_setup.sh
CMD ["python", "-m", "unittest", "tests/test_pacman_dataset.py", "-v"]
