data:
  type: PacmanDataset
  data_dir: ["datasets/pacman"]  # Update with actual path
  resolution: 512
  sequence_length: 5  # Length of action sequences
  load_text_feat: false
  load_vae_feat: false
  transform: default_train
  buffer_size: 1000
  prefetch_factor: 2
  sort_dataset: false
# model config
model:
  model: SanaMS_PACMAN_P1_D12
  image_size: 512
  in_channels: 160
  mixed_precision: fp16
  fp32_attention: true
  load_from:
  resume_from:
  aspect_ratio_type: ASPECT_RATIO_512
  multi_scale: false
  attn_type: linear
  linear_head_dim: 32
  ffn_type: glumbconv
  mlp_acts:
    - silu
    - silu
    - null
  mlp_ratio: 2.5
  use_pe: false
  qk_norm: false
  class_dropout_prob: 0.1
  pe_interpolation: true
  micro_condition: true
  autocast_linear_attn: true
  num_classes: 5

# VAE setting
vae:
  vae_type: dc-ae
  vae_pretrained: mit-han-lab/dc-ae-f32c32-in-1.0
  scale_factor: 0.41407
  vae_latent_dim: 32
  vae_downsample_rate: 32
  sample_posterior: true
# Sana schedule Flow
scheduler:
  predict_v: true
  noise_schedule: linear_flow
  pred_sigma: false
  flow_shift: 1.0
  # logit-normal timestep
  weighting_scheme: logit_normal
  logit_mean: 0.0
  logit_std: 1.0
  vis_sampler: flow_dpm-solver
  train_sampling_steps: 1000

# training setting
train:
  num_workers: 1
  seed: 1
  train_batch_size: 2
  num_epochs: 100
  gradient_accumulation_steps: 1
  grad_checkpointing: true
  gradient_clip: 0.1
  optimizer:
    betas:
      - 0.9
      - 0.999
      - 0.9999
    eps:
      - 1.0e-30
      - 1.0e-16
    lr: 0.0001
    type: CAMEWrapper
    weight_decay: 0.0
  lr_schedule: constant
  lr_schedule_args:
    num_warmup_steps: 2000
  local_save_vis: true # if save log image locally
  visualize: true
  eval_sampling_steps: 500
  log_interval: 20
  save_model_epochs: 1
  save_model_steps: 10000
  work_dir: output/debug
  online_metric: false
  eval_metric_step: 2000
  online_metric_dir: metric_helper
